import jsPDF from "jspdf";

type DiaryRecord = {
  clientName: string;
  staffName: string;
  date: string;
  attendance: string;
  lunch: string;
  transport: string;
  comment: string;
};

export function generateDiaryPDF(records: DiaryRecord[], facilityName: string) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // フォント設定（日本語対応のためBase64フォントが必要な場合は別途追加）
  doc.setFont("helvetica");

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // ヘッダー
  doc.setFontSize(16);
  doc.setTextColor(30, 64, 175);
  doc.text("Facility Daily Report", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(facilityName, margin, y);
  doc.text(records[0]?.date ?? "", pageWidth - margin, y, { align: "right" });
  y += 12;

  // 区切り線
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // テーブルヘッダー
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.setFillColor(248, 250, 252);
  doc.rect(margin, y - 4, pageWidth - margin * 2, 8, "F");
  doc.text("Client", margin + 2, y);
  doc.text("Attn", margin + 50, y);
  doc.text("Lunch", margin + 65, y);
  doc.text("Transport", margin + 82, y);
  doc.text("Comment", margin + 110, y);
  y += 8;

  // データ行
  doc.setTextColor(30, 41, 59);
  records.forEach((rec, i) => {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }
    if (i % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, y - 4, pageWidth - margin * 2, 7, "F");
    }
    doc.setFontSize(8);
    doc.text(rec.clientName.substring(0, 15), margin + 2, y);
    doc.text(rec.attendance, margin + 52, y);
    doc.text(rec.lunch, margin + 67, y);
    doc.text(rec.transport, margin + 84, y);
    const comment = rec.comment.substring(0, 40);
    doc.text(comment, margin + 110, y);
    y += 7;
  });

  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by Fukushi Unei Shido Support - ${new Date().toLocaleString("ja-JP")}`, margin, y);

  doc.save(`daily-report-${records[0]?.date ?? "report"}.pdf`);
}

export function generateMonitoringPDF(
  clientName: string,
  achievement: string,
  issues: string,
  nextGoal: string,
  facilityName: string
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // ヘッダー
  doc.setFontSize(18);
  doc.setTextColor(30, 64, 175);
  doc.text("Monitoring Report", margin, y);
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  doc.text(`Client: ${clientName}`, margin, y);
  doc.text(facilityName, pageWidth - margin, y, { align: "right" });
  y += 7;
  doc.text(`Date: ${new Date().toLocaleDateString("ja-JP")}`, margin, y);
  y += 12;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  const sections = [
    { label: "Achievement / 達成度", content: achievement, color: [5, 150, 105] as [number,number,number] },
    { label: "Issues / 課題", content: issues, color: [217, 119, 6] as [number,number,number] },
    { label: "Next Goal / 次期目標", content: nextGoal, color: [37, 99, 235] as [number,number,number] },
  ];

  sections.forEach((sec) => {
    doc.setFontSize(11);
    doc.setTextColor(...sec.color);
    doc.text(sec.label, margin, y);
    y += 6;

    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    const lines = doc.splitTextToSize(sec.content, pageWidth - margin * 2);
    lines.forEach((line: string) => {
      doc.text(line, margin, y);
      y += 5.5;
    });
    y += 6;
  });

  doc.save(`monitoring-${clientName}-${new Date().toLocaleDateString("ja-JP")}.pdf`);
}
